server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  application:
    name: auth
  redis:
    host: ${REDIS_HOST:192.168.0.103}
    port: ${REDIS_PORT:6379}
    timeout: 50000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://192.168.0.103:3306/xc_user?characterEncoding=utf-8}
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  data:
    mongodb:
      database: testdb
      uri: mongodb://root:root@192.168.0.103:27017
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/xc.keystore
    secret: xuechengkeystore
    alias: xckey
    password: xuecheng
dubbo:
  application:
    name: auth
  registry:
    protocol: zookeeper
    address: 192.168.0.103:2181
  protocol:
    name: dubbo
    port: 20552
  scan:
    base-packages: com.jinli
  consumer:
    timeout: 5000